repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.288
    hooks:
      - id: ruff
        args:
          [
            --fix,
            --exit-non-zero-on-fix,
            --config,
            ./backend/pyproject.toml,
            --extend-select,
            I001,
            --extend-ignore,
            ALL
          ]

  - repo: local
    hooks:
      - id: pre-commit-api-docs
        name: renew api docs
        entry: poetry run --directory backend   ./backend/manage.py spectacular --color --file ./docs/schema.yml
        language: system
        pass_filenames: false
