repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pre-commit-api-docs
        name: renew api docs
        entry: cd backend && poetry  run ./manage.py spectacular --color --file ../docs/schema.yml
        language: system
        pass_filenames: false
      - id: pre-commit-ruff
        name: Lint with ruff
        entry: cd backend && poetry ruff
        language: system
        pass_filenames: false
