repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pre-commit-api-docs
        name: renew api docs
        entry: python ./backend/manage.py spectacular --color --file ./docs/schema.yml
        language: python
        pass_filenames: false
        additional_dependencies:
          [
            django,
            djangorestframework,
            drf-spectacular,
            django-filter,
            django-cors-headers,
            djangorestframework-simplejwt,
            django-extensions,
          ]
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: python ./backend/manage.py makemigrations
        language: python
        pass_filenames: false
        additional_dependencies:
          [
            django,
            djangorestframework,
            drf-spectacular,
            django-filter,
            django-cors-headers,
            djangorestframework-simplejwt,
            django-extensions,
          ]
