version: "3.8"
networks:
  default:
  reverse-proxy:
    external: true
services:
  api:
    container_name: expiration-tracker-api
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    env_file:
      - .env
    volumes:
      - static:/code/static
      - attachments:/code/attachments
    image: expiration-tracker/backend-${ENVIRONMENT}
  nginx:
    container_name: expiration-tracker-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
      args:
        - PUBLIC_URL
        - API_URL
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static
      - attachments:/attachments
    depends_on:
      - api
volumes:
  static:
  attachments:
