version: "3.8"
networks:
  default:
  reverse-proxy:
    external: true
services:
  api:
    container_name: expiration-tracker-api-${ENVIRONMENT}
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    env_file:
      - .env
    networks:
      - reverse-proxy
    volumes:
      - static:/code/static
      - attachments:/code/attachments
    image: expiration-tracker/backend-${ENVIRONMENT}
  nginx:
    container_name: expiration-tracker-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
      args:
        - PUBLIC_URL
        - API_URL
        - ENVIRONMENT
    restart: always
    networks:
      - reverse-proxy
      - default
    env_file:
      - .env
    volumes:
      - static:/static
      - frontend:/usr/share/nginx/html
      - frontend:/usr/share/nginx/html/${PUBLIC_URL}
      - attachments:/attachments
      - ./nginx/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  frontend:
  static:
  attachments:
