openapi: 3.0.3
info:
  title: Expiration tracker API
  version: 1.0.0
  description: App to track expiration dates of medication and other goods
paths:
  /api/auth/:
    post:
      operationId: auth_create
      description: |-
        post:
        Generate REST API token.

        Generate personal REST API token with expired date `ACCESS_TOKEN_LIFETIME_HOURS` or/and
        `ACCESS_TOKEN_LIFETIME_MINUTES` (1 day).

        In a few words - it's an authentication token. To work with API you need to have it, entering your email
        and password. Each time you request to the API, you need to send in header your token like
        `Authorization: JWT eyJ0eXAiOiJKV...`, where `JWT` is header authorization prefix.

        ### Examples

        If data is successfully processed the server returns status code `200`.

        ```json
        {
            "email": "watch.dog@coaxsoft.com",
            "password": "qwerty123"
        }
        ```

        ### Errors

        If there were some error in client data, it sends status code `401` with the error message looks like:

        ```json
        {
            "detail": "No active account found with the given credentials"
        }
        ```
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
        required: true
      responses:
        '200':
          description: No response body
  /api/auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        post:
        Refresh expired JSON Web Token.

        It is used JWT authentication with refresh expiration time = 14 days [Read JWT docs](https://jwt.io/). It
        means, that you have 14 days, from the time your token was generated, to update token with new one. So
        that you need to send your JSON WEB Token.

        ### Examples

        If data is successfully processed the server returns status code `200`.

        ```json
        {
            "refresh": "emskdlgnkngdDFHGergergEGRerRGEgerERE346346vergd456456"
        }
        ```

        ### Errors

        If there were some error in client data, it sends status code `401` with the error message looks like:

        ```json
        {
            "detail": "Token is invalid or expired",
            "code": "token_not_valid"
        }
        ```
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/auth/register/:
    post:
      operationId: auth_register_create
      description: |-
        Register new user in the system

        You need to provide `email`, `first_name`, `last_name`, `password_repeated`
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUp'
          description: ''
  /api/auth/verify/:
    post:
      operationId: auth_verify_create
      description: |-
        post:
        Verify your token (is it valid?)

        To work with API you need to have valid (verified) token which you get after visiting `/auth/token-verify`
        url, entering your token.[Read JWT docs](https://jwt.io/)

        ### Examples

        If data is successfully processed the server returns status code `200`.

        ```json
        {
            "token": "emskdlgnkngdDFHGergergEGRerRGEgerERE346346vergd456456"
        }
        ```

        ### Errors

        If there were some error in client data, it sends status code `401` with the error message looks like:

        ```json
        {
            "detail": "Token is invalid or expired",
            "code": "token_not_valid"
        }
        ```
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerifyRequest'
        required: true
      responses:
        '200':
          description: No response body
  /api/items/items/:
    get:
      operationId: items_items_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - items
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedReprBaseItemList'
          description: ''
    post:
      operationId: items_items_create
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ItemRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReprItem'
          description: ''
  /api/items/items/{id}/:
    get:
      operationId: items_items_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - items
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReprItem'
          description: ''
    put:
      operationId: items_items_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ItemRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReprItem'
          description: ''
    patch:
      operationId: items_items_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this item.
        required: true
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedItemRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedItemRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedItemRequest'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReprItem'
          description: ''
  /api/items/items/choices/:
    get:
      operationId: items_items_choices_retrieve
      description: Get ENUM choices for item
      summary: Get choices for item
      tags:
      - items
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Choice'
          description: ''
  /api/items/items/search/:
    post:
      operationId: items_items_search_create
      description: Send search string to duck duck go
      summary: Perform search
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemSearchRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ItemSearchRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ItemSearchRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
          description: Created. New resource in response
        '400':
          description: Bad request (something invalid)
  /api/items/locations/:
    get:
      operationId: items_locations_list
      description: |-
        create:
        Create Location

        list:
        All Locations

        retrieve:
        Details for single location
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - items
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBaseLocationList'
          description: ''
    post:
      operationId: items_locations_create
      description: |-
        create:
        Create Location

        list:
        All Locations

        retrieve:
        Details for single location
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LocationRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/LocationRequest'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: ''
  /api/items/locations/{id}/:
    get:
      operationId: items_locations_retrieve
      description: |-
        create:
        Create Location

        list:
        All Locations

        retrieve:
        Details for single location
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this location.
        required: true
      tags:
      - items
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: ''
components:
  schemas:
    BaseLocation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 50
      required:
      - id
      - title
    CategoryEnum:
      enum:
      - GOODS
      - MEDICATIONS
      type: string
      description: |-
        * `GOODS` - Goods
        * `MEDICATIONS` - Medications
    Choice:
      type: object
      properties:
        field:
          type: string
        values:
          type: array
          items:
            type: string
      required:
      - field
      - values
    CustomTokenObtainPairRequest:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    ItemRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 50
        category:
          $ref: '#/components/schemas/CategoryEnum'
        quantity:
          type: integer
        expiration_date:
          type: string
          format: date
          nullable: true
        location:
          type: integer
      required:
      - location
      - title
    ItemSearchRequest:
      type: object
      properties:
        barcode:
          type: string
          minLength: 1
          maxLength: 50
      required:
      - barcode
    Location:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 50
        description:
          type: string
      required:
      - id
      - title
    LocationRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 50
        description:
          type: string
      required:
      - title
    PaginatedBaseLocationList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/BaseLocation'
    PaginatedReprBaseItemList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ReprBaseItem'
    PatchedItemRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 50
        category:
          $ref: '#/components/schemas/CategoryEnum'
        quantity:
          type: integer
        expiration_date:
          type: string
          format: date
          nullable: true
        location:
          type: integer
    ReprBaseItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 50
        category:
          $ref: '#/components/schemas/CategoryEnum'
        quantity:
          type: integer
        expiration_date:
          type: string
          format: date
          nullable: true
        location:
          $ref: '#/components/schemas/BaseLocation'
        ttl:
          type: string
          readOnly: true
      required:
      - id
      - location
      - title
      - ttl
    ReprItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 50
        category:
          $ref: '#/components/schemas/CategoryEnum'
        quantity:
          type: integer
        expiration_date:
          type: string
          format: date
          nullable: true
        location:
          $ref: '#/components/schemas/BaseLocation'
        ttl:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - id
      - location
      - title
      - ttl
    SearchResult:
      type: object
      properties:
        title:
          type: string
        href:
          type: string
        body:
          type: string
      required:
      - body
      - href
      - title
    SignUp:
      type: object
      description: Create new user when sign up
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          title: Email address
          maxLength: 255
        first_name:
          type: string
        last_name:
          type: string
      required:
      - email
      - id
    SignUpRequest:
      type: object
      description: Create new user when sign up
      properties:
        email:
          type: string
          format: email
          minLength: 1
          title: Email address
          maxLength: 255
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
      required:
      - access
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - refresh
    TokenVerifyRequest:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - token
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
