name: Build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  docker_build:
    env:
      ENVIRONMENT: "demo"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Make env file
        run: cp ./docs/.env.example .env
      - name: Run compose file build
        run: docker compose build
