name: Demo deploy
on:
  pull_request:
    types: [opened, synchronize]
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - dev
jobs:
  demo_deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Execute deploy of demo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEMO_HOST }}
          username: ${{ secrets.DEMO_USER }}
          password: ${{ secrets.DEMO_PASSWORD }}
          script: |
            cd expiration-tracker
            ./demo_deploy.sh
