name: SonarCloud
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      ENVIRONMENT: "demo"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.6.1
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --with test
        working-directory: ./backend
      - name: Test for coverage
        run: coverage run ./manage.py test && coverage xml
        working-directory: ./backend
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=HomeLabHQ_expiration-tracker
            -Dsonar.organization=homelabhq
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=.
            -Dsonar.verbose=true
