name: SonarCloud
on:
  push:
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      ENVIRONMENT: "demo"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.7.0
          installer-parallel: true
      - name: Install dependencies
        run: poetry -C backend install --with test
      - name: Test for coverage
        run: poetry -C backend run coverage run backend/manage.py test backend &&
          poetry -C backend run coverage xml
      - name: Extract project dir
        shell: bash
        run: echo "BASE_DIR=$(pwd)" >> $GITHUB_ENV
        id: extract_project_dir
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=${BASE_DIR}
            -Dsonar.branch.name=${BRANCH_NAME}
